# Generated by Django 4.2.13 on 2024-07-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='game',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.news'),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(blank=True, to='main.team'),
        ),
        migrations.AlterField(
            model_name='question',
            name='teams',
            field=models.ManyToManyField(blank=True, through='main.TeamQuestionAnswer', to='main.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='played_games_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='teamquestionanswer',
            name='score',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.team'),
        ),
    ]
