# Generated by Django 4.2.13 on 2024-07-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('teams', '0001_initial'),
        ('main', '0002_remove_game_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='game',
        ),
        migrations.AlterField(
            model_name='teamquestionanswer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AlterField(
            model_name='teamquestionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.question'),
        ),
        migrations.AlterField(
            model_name='teamquestionanswer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterField(
            model_name='userteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
