# Generated by Django 4.2.13 on 2024-07-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_news_game_alter_teamquestionanswer_game_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamQuestionAnswer',
        ),
    ]
