# Generated by Django 4.2.13 on 2024-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateTimeField()),
                ('is_over', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(blank=True, to='games.question')),
                ('teams', models.ManyToManyField(blank=True, to='teams.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
