# Generated by Django 4.2.13 on 2024-07-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_description', models.TextField(blank=True, default='')),
                ('game_date', models.DateTimeField()),
                ('game_status', models.CharField(choices=[('active', 'active'), ('finished', 'finished'), ('planned', 'planned')], default='planned')),
            ],
            options={
                'ordering': ['-game_date'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=100)),
                ('question_description', models.TextField()),
                ('question_correct_answer', models.CharField(max_length=255)),
                ('question_weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_team_answer', models.CharField(default='')),
                ('answer_is_correct', models.BooleanField(default=False)),
                ('answer_score', models.FloatField(blank=True, default=0.0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_questions',
            field=models.ManyToManyField(blank=True, to='games.question'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_teams',
            field=models.ManyToManyField(blank=True, to='teams.team'),
        ),
    ]
