# Generated by Django 4.2.13 on 2024-07-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamquestionanswer',
            name='answer_team_answer',
            field=models.CharField(),
        ),
    ]
