# Generated by Django 4.2.13 on 2024-07-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_teamquestionanswer_answer_team_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamquestionanswer',
            old_name='game',
            new_name='game_id',
        ),
        migrations.RenameField(
            model_name='teamquestionanswer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='teamquestionanswer',
            old_name='team',
            new_name='team_id',
        ),
    ]
