# Generated by Django 4.2.13 on 2024-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('captain_id', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('played_games_count', models.IntegerField(blank=True, default=0)),
                ('members_count', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
