# Generated by Django 4.2.13 on 2024-07-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_desc', models.TextField(blank=True, default='')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('captain_id', models.IntegerField(blank=True, unique=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('points', models.FloatField(blank=True, default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('played_games', models.IntegerField(blank=True, default=0)),
                ('team_members', models.ManyToManyField(related_name='team_members', to='main.user')),
            ],
            options={
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
